version: 2
jobs:
  build-android-gtest:
    docker:
      - image: circleci/openjdk:0.3-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "android-gtest/gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "android-gtest/build.gradle" }}
      - run:
          name: Run build
          command: |
            cd android-gtest
            ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "android-gtest/gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "android-gtest/build.gradle" }}
      - store_test_results:
          path: android-gtest/build/test-results/test
      - store_artifacts:
          path: android-gtest/build/test-results/test
          when: always
      - store_artifacts:
          path: android-gtestbuild/libs
workflows:
  version: 2
  workflow:
    jobs:
    - build-android-gtest
